<script lang="ts" setup>
import AppFooter from '@/components/AppFooter.vue'
import AppNavbar from '@/components/AppNavbar.vue'
import router from '@/router'
import { authAPI } from '@/config/api'
import { ref } from 'vue'

const name = ref('')
const email = ref('')
const password = ref('')
const loading = ref(false)

const handleRegister = async () => {
  if (!name.value || !email.value || !password.value) {
    alert('Name, email and password are required')
    return
  }

  loading.value = true

  try {
    // Prepare payload for Spring Boot backend API
    const userData = {
      name: name.value,
      email: email.value,
      password: password.value
    }
    console.log('Sending registration data:', userData)

    // Use the authAPI for cleaner code
    const result = await authAPI.register(userData)

    console.log('Response status:', result.status)
    console.log('Response data:', result.data)

    if (!result.ok) {
      alert(`Error: ${result.data.message || 'Registration failed'}`)
    } else {
      alert(`Registration successful! Your Customer ID is: ${result.data.customerId}`)
      console.log('Customer details:', {
        id: result.data.id,
        name: result.data.name,
        email: result.data.email,
        customerId: result.data.customerId,
        role: result.data.role,
        createdAt: result.data.createdAt
      })

      // Clear form after successful registration
      name.value = ''
      email.value = ''
      password.value = ''

      router.push('/login')
    }
  } catch (err: any) {
    console.error('Registration error:', err)
    const errorMessage = err?.message || 'Something went wrong'
    alert(`Error: ${errorMessage}. Please make sure the backend server is running on port 8081.`)
  } finally {
    loading.value = false
  }
}

// function delete info when input
const handleCancel = () => {
  name.value = ''
  email.value = ''
  password.value = ''
}
</script>

<template>
  <AppNavbar />

  <div class="relative min-h-screen flex justify-center items-center bg-gray-100">
    <!-- Overlay loading ทั้งหน้า -->
    <div v-if="loading" class="absolute inset-0 bg-black/40 flex justify-center items-center z-50">
      <div class="loader"></div>
    </div>

    <!-- Card form -->
    <div class="flex flex-col gap-2 bg-white p-6 rounded shadow-md w-150 z-10">
      <h1 class="font-bold flex justify-center items-center text-xl">Register</h1>

      <fieldset>
        <legend>Name</legend>
        <input
          v-model="name"
          type="text"
          class="input input-bordered w-full"
          placeholder="Type Your Name"
        />
      </fieldset>

      <fieldset>
        <legend>Email</legend>
        <input
          v-model="email"
          type="text"
          class="input input-bordered w-full"
          placeholder="Type Your Email"
        />
      </fieldset>

      <fieldset>
        <legend>Password</legend>
        <input
          v-model="password"
          type="password"
          class="input input-bordered w-full"
          placeholder="Type Your Password"
        />
      </fieldset>

      <!-- Customer ID will be auto-generated by the backend -->

      <div class="flex justify-between mt-4">
        <button @click="handleRegister" :disabled="loading" class="btn btn-info w-1/2 mr-2">
          {{ loading ? 'Registering...' : 'Register' }}
        </button>
        <button @click="handleCancel" class="btn btn-accent w-1/2">Cancel</button>
      </div>
    </div>
  </div>

  <AppFooter />
</template>

<style>
.loader {
  border: 6px solid #f3f3f3;
  border-top: 6px solid #3498db;
  border-radius: 50%;
  width: 60px;
  height: 60px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}
</style>
